--liquibase formatted sql
--changeset antoxakon:2  -- Формат: author:id
--comment: create table visit_history

create table if not exists visit_history
(
    id bigint generated by default as identity primary key,
    visit_id     uuid   not null,
    history_date timestamp(6) not null,
    status varchar(255) not null,
    comment varchar(255)
);